image: node:18

pipelines:
  branches:
    staging:
      - parallel:
          - step:
              name: Install dependencies and build
              caches:
                - node
              script:
                # Install dependencies and build the project
                - yarn install
                - yarn build:ubuntu
          - step:
              name: Deploy and restart application
              script:
                # Decode the Base64-encoded SSH key and save it temporarily
                - echo $SSH_KEY_BASE64 | base64 -d > keys/family-defender.pem
                # Set permissions for the SSH key
                - chmod 600 keys/family-defender.pem
                # Disable SSH strict host key checking and SSH into server
                - mkdir -p ~/.ssh
                - echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
                # Add SSH key for Git authentication
                - eval $(ssh-agent -s)
                - ssh-add keys/family-defender.pem
                # SSH into the server and deploy the application
                - ssh -i keys/family-defender.pem $REMOTE_USER@$REMOTE_HOST "
                  cd /var/www/atlas-free-be && git stash && git pull bitbucket staging && yarn install && yarn build:ubuntu && pm2 reload atlas "
                # Clean up the key after usage
                - rm -f keys/family-defender.pem
