import Joi from "joi";

export const servicesSchema = Joi.object({
    id: Joi.number(),
    organization_id: Joi.number(),
    name: Joi.string().required(),
    street: Joi.string().min(3).max(1600).required(),
    address: Joi.string().min(3).max(1600).required(),
    state: Joi.number().required(),
    city: Joi.string().min(3).max(100).required(),
    zipcode: Joi.string().min(4).max(10).required(),
    disclose_address: Joi.boolean().required(),
    is_organization_address: Joi.boolean().required(),
    service_type: Joi.number(),
    client_slots: Joi.number(),
    slots_beds: Joi.number(),
    start_day_of_service: Joi.date(),
    service_limited: Joi.boolean(),
    enrollment_type: Joi.number(),
    enrollment_period: Joi.number(),
    extension: Joi.boolean(),
    waitlist: Joi.boolean(),
    service_description: Joi.string(),
    minimum_age: Joi.number(),
    maximum_age: Joi.number(),
    genders_served: Joi.array().items(Joi.number()),
    served_to: Joi.array().items(Joi.number()),
    minimum_children_age: Joi.number(),
    maximum_children_age: Joi.number(),
    maximum_children_intake: Joi.number(),
    citizenship_requirement: Joi.array().items(Joi.number()),
    language_requirement: Joi.array().items(Joi.number()),
    out_of_state_relocation: Joi.boolean(),
    trafficking_status: Joi.array().items(Joi.number()),
    legal: Joi.array().items(Joi.number()),
    health_needs: Joi.array().items(Joi.number()),
    medications: Joi.array().items(Joi.number()),
    mental_health_diagnoses: Joi.array().items(Joi.number()),
    physical_accommodations: Joi.array().items(Joi.number()),
    smoking_allowed: Joi.array().items(Joi.number()),
    entry_requirement: Joi.array().items(Joi.number()),
    days_sober: Joi.string(),
    service_model: Joi.array().items(Joi.number()),
    faith_engagement: Joi.number(),
    faith_engagement_practice: Joi.string(),
    service_structure: Joi.number(),
    sleeping_arrangement: Joi.number(),
    staffing_level: Joi.number(),
    teams_diversity: Joi.array().items(Joi.number()),
    service_guidelines: Joi.array().items(Joi.number()),
    support_provided: Joi.array().items(Joi.number()),
    support_offered: Joi.array().items(Joi.number()),
    intake_process: Joi.string(),
    additional_requirements: Joi.string(),
    reason_for_removal: Joi.string(),
    is_submitted: Joi.boolean(),
});

export const clientServiceSchema = Joi.object({
    organization_id: Joi.number().required(),
    user_id: Joi.number().required(),
    client_service_id: Joi.number().required(),
    service_id: Joi.number().required(),
});
