import Joi from "joi";

export const servicesSchema = Joi.object({
    id: Joi.number(),
    organization_id: Joi.number(),
    name: Joi.string().required(),
    street: Joi.string().min(3).max(1600).required(),
    address: Joi.string().min(3).max(1600).required(),
    state: Joi.number().required(),
    city: Joi.string().min(3).max(100).required(),
    zipcode: Joi.string().min(4).max(10).required(),
    disclose_address: Joi.boolean().required(),
    is_organization_address: Joi.boolean().default(0).required(),
    service_type: Joi.number().allow(null).empty("").optional(),
    total_available_slots: Joi.number().allow(null).empty("").optional(),
    slots_beds: Joi.number().allow(null).empty("").optional(),
    start_day_of_service: Joi.date().optional(),
    service_limited: Joi.boolean().default(0).optional(),
    enrollment_type: Joi.number().allow(null).empty("").optional(),
    enrollment_period: Joi.number().allow(null).empty("").optional(),
    extension: Joi.boolean().default(0).optional(),
    waitlist: Joi.boolean().default(0).optional(),
    service_description: Joi.string().empty("").optional(),
    minimum_age: Joi.number().allow(null).empty("").optional(),
    maximum_age: Joi.number().allow(null).empty("").optional(),
    genders_served: Joi.array().items(Joi.number()).optional(),
    served_to: Joi.array().items(Joi.number()).optional(),
    minimum_children_age: Joi.number().allow(null).empty("").optional(),
    maximum_children_age: Joi.number().allow(null).empty("").optional(),
    maximum_children_intake: Joi.number().allow(null).empty("").optional(),
    citizenship_requirement: Joi.array().items(Joi.number()).optional(),
    language_requirement: Joi.array().items(Joi.number()).optional(),
    out_of_state_relocation: Joi.boolean().default(0).optional(),
    trafficking_status: Joi.array().items(Joi.number()).optional(),
    legal: Joi.array().items(Joi.number()).optional(),
    health_needs: Joi.array().items(Joi.number()).optional(),
    medications: Joi.array().items(Joi.number()).optional(),
    mental_health_diagnoses: Joi.array().items(Joi.number()).optional(),
    physical_accommodations: Joi.array().items(Joi.number()).optional(),
    smoking_allowed: Joi.array().items(Joi.number()).optional(),
    entry_requirement: Joi.array().items(Joi.number()).optional(),
    days_sober: Joi.string().empty("").optional(),
    service_model: Joi.array().items(Joi.number()).optional(),
    faith_engagement: Joi.number().allow(null).empty("").optional(),
    faith_engagement_practice: Joi.string().empty("").optional(),
    service_structure: Joi.number().allow(null).empty("").optional(),
    sleeping_arrangement: Joi.number().allow(null).empty("").optional(),
    staffing_level: Joi.number().allow(null).empty("").optional(),
    teams_diversity: Joi.array().items(Joi.number()).optional(),
    service_guidelines: Joi.array().items(Joi.number()).optional(),
    support_provided: Joi.array().items(Joi.number()).optional(),
    support_offered: Joi.array().items(Joi.number()).optional(),
    intake_process: Joi.string().empty("").optional(),
    additional_requirements: Joi.string().empty("").optional(),
    reason_for_removal: Joi.string().empty("").optional(),
    is_submitted: Joi.boolean().default(0),
});

export const clientServiceSchema = Joi.object({
    organization_id: Joi.number().required(),
    user_id: Joi.number().required(),
    client_service_id: Joi.number().required(),
    service_id: Joi.number().required(),
});

export const removeUserSchema = Joi.object({
    organization_id: Joi.number().required(),
    user_id: Joi.number().required(),
    email: Joi.string().email().required(),
})
